### ISSUE TITLE
About the kalman filter velocities

### ISSUE THREAD

**Issue by mpandoko** [mikel-brostrom/Yolov5_DeepSort_OSNet#365]
I am trying to extract the velocity information of the object movements. I thought [vx, vy] in mean are in pixel/seconds, but upon further examination it seems to be unlikely. The kalman filter don't have the time argument. Is it in pixel/frame?

**Comment by mikel-brostrom** [comment]
The Kalman Filter assumes constant velocity in pixels

**Comment by jckhng** [comment]
> I am trying to extract the velocity information of the object movements. I thought [vx, vy] in mean are in pixel/seconds, but upon further examination it seems to be unlikely. The kalman filter don't have the time argument. Is it in pixel/frame?

From what I understand in the code, it is pixel / frame for offline videos where you process every frame. Strictly speaking, it is pixel/"time between which the kalman filter is called". In video steams, the denominator is related to how fast a single frame can be processed. E.g. if it can run at ~10hz, vx and vy are probably around pixel/0.1s. Note that it is not exact and it highly dependent on how fast it can process each frame.

**Comment by mpandoko** [comment]
Thank you, that confirmed my hypothesis. I tried to get the vx and vy in meter by dividing the pixel / (t5-t1), with t5 and t1 in track.py. Do you think that is correct?

**Comment by jckhng** [comment]
Yeah, divide the vx and vy by (t5-t1) to get the velocities in pixel per second, but only for the real time video streams. offline videos will be processed every frame as fast as possible so it won't make sense to use the timings to here, it will still be pixel per frame. There is no way to get meter per second, since meters is dependent on scene and lens and objects distance from camera..

Note that this is sort of a hackish way to get the units you want, ie pixel per second. Probably need to revisit the way kalman filter is used in the code to really get the entire tracking portion of the code to perform the way it is meant to. i.e. estimate both the state and covariances of it's position and velocity in pixel and pixel per seconds.
