### ISSUE TITLE
Can I only count person id ？

### ISSUE THREAD

**Issue by dongxiaolong** [mikel-brostrom/Yolov5_DeepSort_OSNet#406]
I find this project count all detection object ID together. How to only count person id independently if i only want to know how many persons have appeared.

**Comment by mikel-brostrom** [comment]
Without giving it too much though, I would go for:

- Going though each active track

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/8885642c9d049c933c6e1df1d05478dab4a0c37c/deep_sort/sort/tracker.py#L33-L34

- Finding the unique IDs

https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/8885642c9d049c933c6e1df1d05478dab4a0c37c/deep_sort/sort/track.py#L33-L36

- And adding them to a list only if they aren't present in it. Then you can simply take the length of the list at any time in order to know how many people have appeared in the field of view of the camera

**Comment by dongxiaolong** [comment]
> 

Thanks for your reply. I'll try it by your advice.

**Comment by dongxiaolong** [comment]
> Without giving it too much though, I would go for:
> 
> * Going though each active track
> 
> https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/8885642c9d049c933c6e1df1d05478dab4a0c37c/deep_sort/sort/tracker.py#L33-L34
> 
> * Finding the unique IDs
> 
> https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet/blob/8885642c9d049c933c6e1df1d05478dab4a0c37c/deep_sort/sort/track.py#L33-L36
> 
> * And adding them to a list only if they aren't present in it. Then you can simply take the length of the list at any time in order to know how many people have appeared in the field of view of the camera

Thanks for your reply. I'll try it by your advice.

**Comment by AT9991** [comment]
@dongxiaolong I am also facing the same issue. I have two custom classes and want to count its occurrence. If you could solve it can you please comment it here in more details? Thank you
